export const ROLES = {
  ADMIN: "ADMIN",
  SUB_ADMIN: "SUB_ADMIN",
  RECRUITER: "RECRUITER",
  JOB_SEEKER: "JOB_SEEKER",
};

export const USER_TYPE_MAP = {
  [ROLES.RECRUITER]: 3,
  [ROLES.JOB_SEEKER]: 4,
};

export const USER_TYPE_TO_ROLE = {
  1: ROLES.ADMIN,
  2: ROLES.SUB_ADMIN,
  3: ROLES.RECRUITER,
  4: ROLES.JOB_SEEKER,
};
