export const ROLES = {
  ADMIN: "ADMIN",
  SUB_ADMIN: "SUB_ADMIN",
  RECRUITER: "RECRUITER",
  JOB_SEEKER: "JOB_SEEKER",
};

export const USER_TYPE_MAP = {
  [ROLES.RECRUITER]: 3,
  [ROLES.JOB_SEEKER]: 4,
};
