export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  OTP: "/otp",
  
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  CHANGE_PASSWORD: "/change-password",

  PUBLIC_JOBS: "/jobs",
  PUBLIC_JOB_DETAIL: "/jobs/:id",

  SEEKER_JOBS: "/seeker/jobs",
  SEEKER_JOB_DETAIL: "/seeker/jobs/:id",
  SEEKER_APPLICATIONS: "/seeker/applications",
  SEEKER_APPLICATION_DETAIL: "/seeker/applications/:id",
  SEEKER_SAVED_JOBS: "/seeker/saved-jobs",
  SEEKER_JOB_ALERTS: "/seeker/job-alerts",
  SEEKER_PROFILE: "/seeker/profile",
  SEEKER_MESSAGES: "/seeker/messages",

  RECRUITER_DASHBOARD: "/recruiter/dashboard",
  RECRUITER_JOBS: "/recruiter/jobs",
  RECRUITER_JOB_ADD: "/recruiter/jobs/add",
  RECRUITER_JOB_PUBLISH: "/recruiter/jobs/publish",
  RECRUITER_JOB_EDIT: "/recruiter/jobs/:id/edit",
  RECRUITER_APPLICATIONS: "/recruiter/applications",
  RECRUITER_MESSAGES: "/recruiter/messages",
  RECRUITER_PROFILE: "/recruiter/profile",
  RECRUITER_COMPANY_PROFILE: "/recruiter/company-profile",

  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_JOBS: "/admin/jobs",
  ADMIN_APPLICATIONS: "/admin/applications",
  ADMIN_USERS: "/admin/users",
  ADMIN_SUB_ADMINS: "/admin/sub-admins",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_ACCESS_RIGHTS: "/admin/access-rights/:userId",
  ADMIN_PROFILE: "/admin/profile",
};
