<?php

namespace App\Constants;

class EmailTemplateConstants
{
    public const SEEKER_APPLICATION_VIEWED_EMAIL = 'SEEKER_APPLICATION_VIEWED_EMAIL';

    public const SEEKER_WITHDRAW_JOB_APPLICATION_EMAIL = 'SEEKER_WITHDRAW_JOB_APPLICATION_EMAIL';

    public const RECRUITER_WITHDRAW_JOB_APPLICATION_EMAIL = 'RECRUITER_WITHDRAW_JOB_APPLICATION_EMAIL';

    public const FORGOT_PASSWORD_OTP_EMAIL = 'FORGOT_PASSWORD_OTP_EMAIL';
}
